### ISSUE TITLE
Issue Identifying the 2-PVU Surface in GFSv16

### ISSUE THREAD

**Issue by AliciaBentley-NOAA** [NOAA-EMC/UPP#340] opened 2021-06-23 18:41 UTC
I was recently contacted by several GFS users about an issue that they've been seeing in GFSv16. Specifically, they've noticed strange spots on the 2-PVU surface in both the GFS analyses and forecasts. These spots appeared for the first time immediately after the GFSv16 upgrade at 1200 UTC March 22nd (when the model top was raised from 1 hPa to 0.1 hPa). 

My hypothesis was that the top-down search for the 2-PVU surface is starting at the new model top in GFSv16 (0.1 hPa) and is running into erroneous 2-PVU values in the stratosphere before it finds the actual tropopause. My recommendation would be to start the search for the 2-PVU surface (*and other PV surfaces*) at 1 hPa like we did in GFSv15, and then work our way down so that we aren't erroneously sampling the stratosphere anymore. This solution is very similar to the GFSv16 CAPE fix in 2020, but instead of stopping our upward search at 1 hPa, we would be starting our downward search at 1 hPa. Thanks!

![spots_2pvu_pressure](https://user-images.githubusercontent.com/65627908/123150811-c85d2b80-d430-11eb-8496-8aa9652c33fd.png)

**Comment by WenMeng-NOAA** [comment] 2021-06-30 13:50
I tried the fixes  as 
```
call rsearch1(km,p,1,100,l3)
km1=km-l3+1
do  k=1,kpv
      call rsearch1(km1,p,1,pvpb(k),l1)
      call rsearch1(km1,p,1,pvpt(k),l2)
!     l1=l1+1
      l = 0
      if(pv(k) >= 0.) then
!       do lu=l2-1,l1,-1
!       do lu=l2,l1-1 ! Chuang: post counts top down
        do lu=l2+2,l1 ! Chuang: post counts top down
!         if(pv(k)<pvu(lu+1).and.pv(k)>=pvu(lu)) then
          if(pv(k) >= pvu(lu+1).and.pv(k) < pvu(lu)) then
            call rsearch1(km1,p,1,p(lu)+pd,ld)
!           if(all(pv(k)>=pvu(ld:lu-1))) then
            if(all(pv(k) >= pvu(lu+1:ld))) then
              l = lu
              exit
            endif
          endif
        enddo
      else
!       do lu=l2-1,l1,-1
!       do lu=l2,l1-1 ! Chuang: post counts top down
        do lu=l2+2,l1 ! Chuang: post counts top down
!         if(pv(k)>pvu(lu+1).and.pv(k)<=pvu(lu)) then
          if(pv(k) <= pvu(lu+1).and.pv(k) > pvu(lu)) then
            call rsearch1(km1,p,1,p(lu)+pd,ld)
!           if(all(pv(k)<=pvu(ld:lu-1))) then
            if(all(pv(k) <= pvu(lu+1:ld))) then
              l = lu
              exit
            endif
          endif
        enddo
      endif
```
That fixes didn't solve the issue. The further investigation is needed.

**Comment by WenMeng-NOAA** [comment] 2021-07-02 17:39
Here are some issue case identifying:
![image](https://user-images.githubusercontent.com/48260754/124313347-bff6a600-db3e-11eb-84e0-513aefa0118f.png)
![image](https://user-images.githubusercontent.com/48260754/124313755-4dd29100-db3f-11eb-9895-85fd5ade6fee.png)

**Comment by AliciaBentley-NOAA** [comment] 2021-07-02 17:43
Hi Wen. Can you confirm the date in the top image, please? Thanks!

**Comment by WenMeng-NOAA** [comment] 2021-07-02 18:12
@AliciaBentley-NOAA My mistakes about titles. Correct them. Thanks for catching.

**Comment by AliciaBentley-NOAA** [comment] 2021-07-02 18:30
Hi Wen. Thank you! I just wanted to make sure that we were comparing GFSv15 and GFSv16 on the same date and time.

**Comment by WenMeng-NOAA** [comment] 2021-07-06 00:32
Here are the comparison of GFS V15 and GFS V16 (EMC real-time parallel run) for 20201222.
![image](https://user-images.githubusercontent.com/48260754/124530456-8cd04300-ddda-11eb-8180-33549d7d477b.png)
![image](https://user-images.githubusercontent.com/48260754/124526217-1fb7b000-ddd0-11eb-96a1-a02048f6f2b5.png)

**Comment by AliciaBentley-NOAA** [comment] 2021-07-06 00:40
Hi Wen. The two images above depict very different pressure patterns. Features do not match up between the two images, despite this being an analysis of the same date. This leads me to believe that they do not show the same date. Can you please explain what it going on here?

**Comment by AliciaBentley-NOAA** [comment] 2021-07-06 01:01
Would it be possible to pick a time during the 30-day parallel production test (so that we know it's the final configuration of GFSv16 being cycled)? The 2021030118 time that you showed a few posts ago would work well!

**Comment by WenMeng-NOAA** [comment] 2021-07-06 01:04
@AliciaBentley-NOAA I have the same doubt as you. These data files were retrieved from HPSS:
1) GFS V15: /NCEPPROD/hpssprod/runhistory/rh2020/202012/20201222/com_gfs_prod_gfs.20201222_00.gfs_pgrb2.tar
2) GFS V16: /NCEPDEV/emc-global/5year/emc.glopara/WCOSS_D/gfsv16/v16rt2/gfsa.tar

You may access data files from subdirectories of gfs15 and gfsv16 at  /u/Wen.Meng/ptmp/gfs_data on Mars.

**Comment by WenMeng-NOAA** [comment] 2021-07-06 01:08
@AliciaBentley-NOAA Do you know the location of HPSS for NCO's 30-day parallel run? I looked around the HPSS and didn't get it.

**Comment by AliciaBentley-NOAA** [comment] 2021-07-06 01:27
The GFSv15 path that you wrote above says "**202102**22" (February 22nd, 2021), but the image title says "**202012**22" (December 22nd, 2020). The second image correctly shows December 22nd, 2020 based on a comparison with a [2-PVU archive image](http://www.atmos.albany.edu/student/heathera/dt/nam/15001.png) valid at the same time.

I do not know the path to the GFSv16 30-day parallel data on HPSS. I would recommend asking Russ and Fanglin. Thanks!

**Comment by WenMeng-NOAA** [comment] 2021-07-06 01:51
@AliciaBentley-NOAA Your are right. I retrieved GFS V15 from 2020122200. The GFS V15 plot was regenerated. Now patterns from two plots should make sense.

**Comment by yangfanglin** [comment] 2021-07-06 04:39
GFS.v16 model top  is at 0.01 hPa (~80km).  GFS.v15 model top is at 0.2 hPa (~55km).   two [ PVU](https://glossary.ametsoc.org/wiki/Potential_vorticity)=2 surfaces can occur in the vertical at the same location since temperature decreases with height in both the troposphere and mesosphere (std profile).

**Comment by WenMeng-NOAA** [comment] 2021-07-06 05:03
Another case of GFS V15 and GFS V16 comparison:
![image](https://user-images.githubusercontent.com/48260754/124544811-db3f0b00-ddf5-11eb-969e-e389d6012224.png)
![image](https://user-images.githubusercontent.com/48260754/124544840-ec881780-ddf5-11eb-8b7c-d4fe906191c3.png)

**Comment by AliciaBentley-NOAA** [comment] 2021-07-06 12:45
Hi Wen. Would it be possible to update these plots to use the more detailed colorbar that you've used in previous plots (color changes every 5,000)? I think a more detailed colorbar might show the GFSv16 spots better. Thanks!

And I agree, Fanglin. We're trying to see what can be done to find the correct 2-PVU tropopause in GFSv16.

**Comment by WenMeng-NOAA** [comment] 2021-07-06 13:37
Update comparison plots:

- GFS V15 -- /u/Wen.Meng/noscrubd6/ncep_post/gfs_data/gfsv15/gfs.20210301/18/gfs.t18z.pgrb2.0p25.f000 on mars
- GFS V16 -- /u/Wen.Meng/noscrubd6/ncep_post/gfs_data/gfsv16/gfs.20210301/18/gfs.t18z.pgrb2.0p25.f000 on mars

![image](https://user-images.githubusercontent.com/48260754/124609627-cdad7380-de3d-11eb-8d00-fc00e01c8b4d.png)

**Comment by AliciaBentley-NOAA** [comment] 2021-07-06 13:44
Thanks, Wen. Would it be possible to see the results of your tests before tomorrow's meeting? Specifically, can we see the results of lowering the model top for the isobaric PVU computation? You and Huiya have both mentioned the result was too smooth, and I think that will be important to see to understand where to go from here. 

Also, based a more recent June analysis, it looks like this issue gets worse in the warm season (much like the CAPE model-top issue did). Hopefully a fix can be found. 

![123150811-c85d2b80-d430-11eb-8496-8aa9652c33fd](https://user-images.githubusercontent.com/65627908/124610609-a905cb80-de3e-11eb-9469-d7fecb0f8813.png)

**Comment by WenMeng-NOAA** [comment] 2021-07-06 14:39
@AliciaBentley-NOAA I have been retesting the fix starting at the subroutine p2pv in the file GFSPOST.F. I would like some suggestions on fix  of 1 hPa cap in this subroutine.

**Comment by WenMeng-NOAA** [comment] 2021-07-06 15:27
Added 1 hPa cap in the subroutine "p2pv" as:
![image](https://user-images.githubusercontent.com/48260754/124626852-0a349b80-de4d-11eb-87d9-ed8eace32ef5.png)

**Comment by GeoffManikin-NOAA** [comment] 2021-07-06 15:32
hi Wen.    I'm a little confused here, as I thought you said (and I see where it's set in the code) that there is what's intended to be a cap at 50 hPa.    If that were working as intended, it seems like it would solve the issue, as it appears that we're finding a second PVU=2 surface somewhere between 55 and 80 km.     My suggestion would be to pick a point in the chosen test case where the PVU=2 fields look "weird" and then print out the values from the column search to see whether the checks are sampling the stratosphere.

**Comment by WenMeng-NOAA** [comment] 2021-07-06 15:34
With the fixes above, the changes in pres2pv in master file are:
![image](https://user-images.githubusercontent.com/48260754/124627697-c5f5cb00-de4d-11eb-97e4-3f6791caa201.png)

![image](https://user-images.githubusercontent.com/48260754/124628057-1a994600-de4e-11eb-80a2-eee7b3e4369e.png)

**Comment by AliciaBentley-NOAA** [comment] 2021-07-06 15:42
Thanks, Wen! This fix has helped a lot (there are fewer strange spots) and is a lot closer to what we expect to see. Unfortunately, not all of the strange spots were removed with this fix alone. This tells me that even though you've fixed the vertical search for pres2pv, there may still be issues in the isobaric PVU computation (which also uses a too high model-top and occurs first). Would it be possible to fix the model top in that part of the code as well, rerun the test, and send us new images?

**Comment by WenMeng-NOAA** [comment] 2021-07-07 00:26
Add a cap in  the subroutine pvetc which compute theta, pvu at model layers.
![image](https://user-images.githubusercontent.com/48260754/124682300-7092db80-de98-11eb-8dae-5fdbcd233ebf.png)

**Comment by WenMeng-NOAA** [comment] 2021-07-07 00:32
Here is the  fixes in pvtec:
![image](https://user-images.githubusercontent.com/48260754/124682561-147c8700-de99-11eb-82c9-490440fa9b41.png)

**Comment by AliciaBentley-NOAA** [comment] 2021-07-07 01:45
Thanks, Wen. It appears that adding an upper bound on the pvetc subroutine makes the output noisier than before. I thought the issue with adding the upper bound to pvetc subroutine was that it made the field too smooth. I'm confused about getting the opposite results from the second test. Perhaps the first test also made the field look like this (too noisy)?

The image above suggests that it is not the pvetc subroutine that is contributing to the remaining spots that we are seeing on the pres2pvu surface. The dark spots are still visible in the latest image over eastern Greenland, north of Alaska, etc. I'm happy that changing the upper bound in pres2pv helped as much as it did in your previous post (~75% better), but it didn't quite get us where we would like to be. It looks like the remaining spots are originating somewhere else in the code.

**Comment by WenMeng-NOAA** [comment] 2021-07-07 01:52
In my test last week, the cap was in pvetc only. That made the whole field smooth.  In my latest plot, two caps are applied, one in pvtec, another in p2pv.

**Comment by AliciaBentley-NOAA** [comment] 2021-07-07 01:58
Thanks for your work on this, Wen. I don't have anything else to add right now. I'm happy that our suggestion to add a "lower" upper bound to p2pv appears to have helped as much as it did, but it's a shame that it doesn't totally fix it. Perhaps other possible causes of the remaining spots can be discussed during tomorrow's meeting!

**Comment by WenMeng-NOAA** [comment] 2021-07-07 02:38
The corrections are applied in kd, ku computation in pvtec:
![image](https://user-images.githubusercontent.com/48260754/124692016-cf615080-deaa-11eb-8c66-2319c54f341c.png)

![image](https://user-images.githubusercontent.com/48260754/124691768-637ee800-deaa-11eb-8785-177366e2ed30.png)

**Comment by AliciaBentley-NOAA** [comment] 2021-07-07 02:55
Hi Wen. What was the issue with the first plot that had both caps applied? Your new plot looks more reasonable!

Adding an upper bound to pvetc does not appear to fix the remaining spots on the 2-PVU pressure surface (see below). The spots are still there in the second image. I do not know the UPP code enough to speculate on what is causing the remaining spots. Hopefully others have some ideas that they can bring to tomorrow's meeting.    

![124628057-1a994600-de4e-11eb-80a2-eee7b3e4369e](https://user-images.githubusercontent.com/65627908/124693000-a346cf00-deac-11eb-8b1c-92ac75f32caa.png)

![124691768-637ee800-deaa-11eb-8785-177366e2ed30](https://user-images.githubusercontent.com/65627908/124693023-acd03700-deac-11eb-9494-c420ef2e3850.png)

**Comment by AliciaBentley-NOAA** [comment] 2021-07-07 03:56
One additional thought: Perhaps 1 hPa is still too high up in the atmosphere and allows for incorrect 2-PVU surfaces to be identified. Huiya said in a previous email that the upper bound for the vertical search was 50 hPa in both models, but that may not have ultimately been the case if "lowering" the upper bound to 1 hPa removed ~75% of the dark spots in Wen's test. Should the upper bound really be 50 hPa? An interesting test might be to lower the upper bound from 1 hPa to 50 hPa and see if all of the dark spots disappear!

**Comment by HuiyaChuang-NOAA** [comment] 2021-07-07 12:49
> Hi Wen. The two images above depict very different pressure patterns. Features do not match up between the two images, despite this being an analysis of the same date. This leads me to believe that they do not show the same date. Can you please explain what it going on here?

@AliciaBentley-NOAA I actually think the two matched up quite well.  The PUV fields are highly sensitive and with vertical coordinates being so different between the two versions, this kind of difference isn't that bad

**Comment by AliciaBentley-NOAA** [comment] 2021-07-07 13:00
@HuiyaChuang-NOAA Yes, they are very similar now. Wen went back and corrected the images after the fact. If you go to the "edited" option above her message, you can see how different they originally were. They looked like this (because they showed February 22nd, 2021 and December 22nd, 2020, respectively):

<img width="569" alt="Screen Shot 2021-07-07 at 8 59 04 AM" src="https://user-images.githubusercontent.com/65627908/124763181-b1730a80-df01-11eb-97c9-14e63a5fc54f.png">

**Comment by HuiyaChuang-NOAA** [comment] 2021-07-07 14:23
Let's wait till after this afternoon's meeting to make any changes

**Comment by HuiyaChuang-NOAA** [comment] 2021-07-07 18:16
@WenMeng-NOAA @yangfanglin @AliciaBentley-NOAA @GeoffManikin-NOAA 
I took a look at the subroutine P2PV.  To identify a constant PV=2 surface, the entire layer of 25 mb has to have PV>2.
This may be too strict now that we have 127 layers instead of 64.  Let's talk with Fanglin at the meeting.  I also reached out
to Mark I. who was the original author of this subroutine.

**Comment by WenMeng-NOAA** [comment] 2021-07-07 19:55
@HuiyaChuang-NOAA My working case is set up at /u/Wen.Meng/noscrubd6/ncep_post/gfsv16/EMC_post. You may use drive script run_post_fv3gfsv16_WCOSS_DELL_P3.sh to submit the job for the test case from 2021062212. There is 1 hPa cap applied in  the subroutine p2pv. Please let me know if you need further information from me. Thanks!

**Comment by HuiyaChuang-NOAA** [comment] 2021-08-23 17:11
@WenMeng-NOAA  I will pick up your test and start looking at this.

**Comment by WenMeng-NOAA** [comment] 2021-08-23 17:17
@HuiyaChuang-NOAA That would be great. Please let me know if you have changes for me to pick up. Thanks!

**Comment by HuiyaChuang-NOAA** [comment] 2021-08-25 17:08
@AliciaBentley-NOAA @GeoffManikin-NOAA @WenMeng-NOAA 

Using the printouts from Wen for the 2021062212 case, I noticed that the the grid points with PV=2 level identified much higher than surrounding points had 2-3 layers that met PV<=2 over 25 mb while the sounding normal gird points have one deep layer of PV=2 at lower levels.

I decided to change 25 mb depth criteria to meet PV<=2 to 50 mb and it fixed the issue for this case.  I've attached 
three plots 1) operational, 2) new with deeper PV<=2 criteria, 3) difference.  

I want to point out that although this new criteria fixed spotty PV issues but it also resulted in large PV field
changes near transition zones.  Thus, my proposal is:
1) update UPP develop with this change
2) run this change in GFS V17 parallel for evaluation by MEG, CPC, and perhaps Albany group.

This will ensure the change works for all seasons.  Please let me know your thought.

![pres2pv_org](https://user-images.githubusercontent.com/56728916/130834662-2f2c8b9b-da23-466a-ab8d-d5b4bc6ef108.png)
![GFS_PRES2pv_new](https://user-images.githubusercontent.com/56728916/130832744-e51d48c5-7add-4a79-97f3-87109bcc9cce.png)
![GFS_PRES2pv_diff](https://user-images.githubusercontent.com/56728916/130832764-4580ac4f-0526-41b4-a165-756e2cf7452f.png)

**Comment by HuiyaChuang-NOAA** [comment] 2021-08-25 21:18
Huiya sent the following email to Jason, Fanglin, and Daryl, reiterating the proposed fix, showed the plots,
and proposed committing this fix to UPP develop and test the changes in GFS V17 parallel.
------------------------------------------------------------------------------------------------------
Hi, all, 

Using the printouts from Wen for the 2021062212 case, I noticed that the problematic grid points with PV=2 level identified much higher than surrounding points had 2-3 shallow layers that met PV<=2 over 25 mb criteria in UPP, while the sounding normal grid points have one deep layer of PV<=2 at lower levels.

I decided to change the 25 mb depth criteria to 50 mb and ran the test case set up by Wen.  It fixed the issue for this case! I've attached three plots 1) operational, 2) new with 50 mb PV<=2 criteria, 3) difference.

I want to point out that although this new criteria fixed spotty PV issues but it also introduced large PV differences near transition zones. Thus, my proposal is:

update UPP develop with this change
run this change in GFS V17 parallel for evaluation by MEG, CPC, and perhaps Albany group.
This will ensure the change is robust enough to work for all seasons. Please let me know your thoughts.



Huiya
----------------------------------------------------------------------------------------------------------------------------------

**Comment by HuiyaChuang-NOAA** [comment] 2021-08-25 21:23
Jason and Alicia replied to above email and agreed we can wait to test this fix in GFS V17 parallel. (email attached)
Huiya requested Alicia and Daryl let users know a fix has been identified and will be tested in GFS V17 parallel.
Wen is starting a PR to commit this one-line fix.

-----------------------------------------------------------------------------------------------------------------------
Agreed, implementation and testing of the fix should wait until GFS v17. Thanks,

Jason
-------------------------------------------------------------------------------------------------------------------

**Comment by WenMeng-NOAA** [comment] 2021-08-31 14:43
Wen picked up Huiya's changes and submit PR #371 to develop branch.

**Closed as completed** 2021-09-01 16:58 UTC
Labels: enhancement

**Comment by WenMeng-NOAA** [comment] 2021-09-01 17:02
The changed results in GFS master are:
[Wen.Meng@m71a1 ptmp]$ cat gfs.20200204/gfs.t00z.master.grb2f006.diff
1047:2866603169:UGRD:PV=5e-07 (Km^2/kg/s) surface:rpn_corr=0.93192:rpn_rms=7.56224
1048:2870273970:VGRD:PV=5e-07 (Km^2/kg/s) surface:rpn_corr=0.925165:rpn_rms=5.68945
1049:2873906091:TMP:PV=5e-07 (Km^2/kg/s) surface:rpn_corr=0.885917:rpn_rms=8.81512
1050:2877909539:HGT:PV=5e-07 (Km^2/kg/s) surface:rpn_corr=0.927551:rpn_rms=1765.72
1051:2884240192:PRES:PV=5e-07 (Km^2/kg/s) surface:rpn_corr=0.940127:rpn_rms=5291.89
1052:2890511877:VWSH:PV=5e-07 (Km^2/kg/s) surface:rpn_corr=0.656408:rpn_rms=0.00746685
1053:2893335684:UGRD:PV=-5e-07 (Km^2/kg/s) surface:rpn_corr=0.932052:rpn_rms=7.02596
1054:2896913032:VGRD:PV=-5e-07 (Km^2/kg/s) surface:rpn_corr=0.923806:rpn_rms=5.3751
1055:2900441680:TMP:PV=-5e-07 (Km^2/kg/s) surface:rpn_corr=0.852736:rpn_rms=10.6592
1056:2904372884:HGT:PV=-5e-07 (Km^2/kg/s) surface:rpn_corr=0.899942:rpn_rms=1892.52
1057:2910423202:PRES:PV=-5e-07 (Km^2/kg/s) surface:rpn_corr=0.90895:rpn_rms=5953.33
1058:2916384487:VWSH:PV=-5e-07 (Km^2/kg/s) surface:rpn_corr=0.674862:rpn_rms=0.00704953
1059:2919108277:UGRD:PV=1e-06 (Km^2/kg/s) surface:rpn_corr=0.942035:rpn_rms=7.13053
1060:2922560475:VGRD:PV=1e-06 (Km^2/kg/s) surface:rpn_corr=0.939423:rpn_rms=5.09779
1061:2925960449:TMP:PV=1e-06 (Km^2/kg/s) surface:rpn_corr=0.935742:rpn_rms=5.76905
1062:2929525230:HGT:PV=1e-06 (Km^2/kg/s) surface:rpn_corr=0.947716:rpn_rms=1439.33
1063:2935461896:PRES:PV=1e-06 (Km^2/kg/s) surface:rpn_corr=0.956723:rpn_rms=3935.28
1064:2941300429:VWSH:PV=1e-06 (Km^2/kg/s) surface:rpn_corr=0.7392:rpn_rms=0.00707706
1065:2944044307:UGRD:PV=-1e-06 (Km^2/kg/s) surface:rpn_corr=0.942492:rpn_rms=6.42849
1066:2947485537:VGRD:PV=-1e-06 (Km^2/kg/s) surface:rpn_corr=0.940904:rpn_rms=4.63934
1067:2950883407:TMP:PV=-1e-06 (Km^2/kg/s) surface:rpn_corr=0.925229:rpn_rms=6.42954
1068:2954517920:HGT:PV=-1e-06 (Km^2/kg/s) surface:rpn_corr=0.938087:rpn_rms=1397.7
1069:2960464108:PRES:PV=-1e-06 (Km^2/kg/s) surface:rpn_corr=0.949248:rpn_rms=3709.53
1070:2966288388:VWSH:PV=-1e-06 (Km^2/kg/s) surface:rpn_corr=0.754228:rpn_rms=0.00649333
1071:2969012309:UGRD:PV=1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.946744:rpn_rms=6.86273
1072:2972317348:VGRD:PV=1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.946324:rpn_rms=4.75222
1073:2975560499:TMP:PV=1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.951544:rpn_rms=4.57244
1074:2978831108:HGT:PV=1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.954163:rpn_rms=1302.28
1075:2984471252:PRES:PV=1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.960887:rpn_rms=3366.91
1076:2989987302:VWSH:PV=1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.782463:rpn_rms=0.00681633
1077:2992647950:UGRD:PV=-1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.946032:rpn_rms=6.17459
1078:2995947882:VGRD:PV=-1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.948066:rpn_rms=4.27078
1079:2999202238:TMP:PV=-1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.948222:rpn_rms=4.88417
1080:3002550808:HGT:PV=-1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.947997:rpn_rms=1232.01
1081:3008250146:PRES:PV=-1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.959533:rpn_rms=2978.36
1082:3013803177:VWSH:PV=-1.5e-06 (Km^2/kg/s) surface:rpn_corr=0.791046:rpn_rms=0.00620596
1083:3016472310:UGRD:PV=2e-06 (Km^2/kg/s) surface:rpn_corr=0.950177:rpn_rms=6.58989
1084:3019678488:VGRD:PV=2e-06 (Km^2/kg/s) surface:rpn_corr=0.950283:rpn_rms=4.52117
1085:3022818290:TMP:PV=2e-06 (Km^2/kg/s) surface:rpn_corr=0.961302:rpn_rms=3.83256
1086:3025891501:HGT:PV=2e-06 (Km^2/kg/s) surface:rpn_corr=0.958527:rpn_rms=1209.96
1087:3031333459:PRES:PV=2e-06 (Km^2/kg/s) surface:rpn_corr=0.963998:rpn_rms=3007.15
1088:3036632860:VWSH:PV=2e-06 (Km^2/kg/s) surface:rpn_corr=0.808085:rpn_rms=0.00662238
1089:3039228717:UGRD:PV=-2e-06 (Km^2/kg/s) surface:rpn_corr=0.947847:rpn_rms=6.01886
1090:3042423161:VGRD:PV=-2e-06 (Km^2/kg/s) surface:rpn_corr=0.951927:rpn_rms=4.03932
1091:3045566328:TMP:PV=-2e-06 (Km^2/kg/s) surface:rpn_corr=0.958361:rpn_rms=4.14768
1092:3048702293:HGT:PV=-2e-06 (Km^2/kg/s) surface:rpn_corr=0.951392:rpn_rms=1162.48
1093:3054186137:PRES:PV=-2e-06 (Km^2/kg/s) surface:rpn_corr=0.961782:rpn_rms=2710.73
1094:3059505353:VWSH:PV=-2e-06 (Km^2/kg/s) surface:rpn_corr=0.811763:rpn_rms=0.00602733
