### ISSUE TITLE
Use main spack repo

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/UPP#608] opened 2022-12-19 19:41 UTC
The CI currently uses the NOAA-EMC version of Spack for both the gcc and intel workflows. Our eventual goal is to support NCEPLIBS and related packages completely through the main Spack repository. As of right now, it should make no difference which one is used, but it would be best to transition to the main Spack repo as soon as possible.

**Comment by WenMeng-NOAA** [comment] 2022-12-19 21:48
@AlexanderRichert-NOAA Would you work on the PR to help us for  this UPP CI configuration transition? Thanks!

**Comment by AlexanderRichert-NOAA** [comment] 2022-12-19 21:56
@WenMeng-NOAA Can you add me as an assignee?

**Comment by WenMeng-NOAA** [comment] 2022-12-20 00:01
@AlexanderRichert-NOAA You may find the UPP code contribution procedure at 
https://github.com/NOAA-EMC/UPP/wiki/UPP-Code-Development#contribute-changes-in-upp-main-development-branch-develop

Thanks!

**Comment by WenMeng-NOAA** [comment] 2023-01-19 01:28
@AlexanderRichert-NOAA The working branch from our UPP developer's folk failed at CI for both gcc/intel build, please see
https://github.com/SamuelTrahanNOAA/UPP/actions/runs/3950535967/jobs/6763280479

Could you help us on it? Thanks!

**Comment by gspetro-NOAA** [comment] 2024-11-27 23:25
@WenMeng-NOAA Can this issue be closed? The CI we have currently seems to be working as intended.

**Comment by WenMeng-NOAA** [comment] 2024-11-28 00:44
@AlexanderRichert-NOAA Do you think any updates are needed?

**Comment by AlexanderRichert-NOAA** [comment] 2024-11-28 01:11
At this point the JCSDA fork (formerly NOAA-EMC) of Spack is pretty well in sync with main Spack, so I don't think it makes much difference. This can be closed if using the fork hasn't led to any issues.

**Comment by WenMeng-NOAA** [comment] 2024-11-28 01:16
@AlexanderRichert-NOAA Thanks for clarifying. I will close it.

**Closed as completed** 2024-11-28 01:16 UTC
Labels: enhancement
