### ISSUE TITLE
requesting addition of foundation temperature to surface grib2 files

### ISSUE THREAD

**Issue by LydiaStefanova-NOAA** [NOAA-EMC/UPP#406] opened 2021-10-14 17:51 UTC
The coupled modeling group is requesting that foundation temperature be added as a new variable to the surface grib2 files.  

The foundation temperature is currently output in the surface netcdf files under the name "tref". An example surface netcdf with tref is here: 

_/scratch1/NCEPDEV/stmp2/Lydia.B.Stefanova/upp_issues/gfs.20130701/00/atmos/gfs.t00z.sfcf006.nc_

Information about the grib2 code for foundation temperature can be found on the fourth line of the table here: https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-3-5.shtml

**Comment by HuiyaChuang-NOAA** [comment] 2021-11-10 15:12
Huiya is working on adding foundation temperature in a branch in her UPP fork.

**Comment by HuiyaChuang-NOAA** [comment] 2021-11-16 22:13
1. Huiya created a branch: Add_tref to her fork.
2. She modified UPP source code to read and output foundation temperature
3. She modified post_avblflds.xml, postcntrl_gfs_flux_f00.xml,  postcntrl_gfs_flux.xml, postcntrl_gfs_f00_two.xml, postcntrl_gfs_two.xml to add foundation  to inline and offline GFS post control files
4. Ran two post runs using model output from Coupling group using updated source code and control files
5. Confirmed foundation temperature is added to post processing output
6. Sent the plot to Lydia, Jessica who confirm the post processed foundation T is similar to the one plotted from model surface output.
7. Committed to the changes to Add_tref branch in her fork

**Comment by WenMeng-NOAA** [comment] 2021-11-17 23:00
@LydiaStefanova-NOAA and @HuiyaChuang-NOAA The grib2 table 4.2-3-5 is for satellite remote sensing products. The foundation temperature output from FV3 is that category?

**Comment by HuiyaChuang-NOAA** [comment] 2021-11-18 18:25
> @LydiaStefanova-NOAA and @HuiyaChuang-NOAA The grib2 table 4.2-3-5 is for satellite remote sensing products. The foundation temperature output from FV3 is that category?

@WenMeng-NOAA it appeared that the Grib2 template table params_grib2_tbl_new already used this table to define foundation temperature before I added this variable to UPP so it should be ok

**Comment by WenMeng-NOAA** [comment] 2021-11-18 19:52
@HuiyaChuang-NOAA I mean if the users will think this is a satellite remote sensing product since FDNSSTMP is in from the grib2 table for satellite remote sensing category. If you and @LydiaStefanova-NOAA think it is good, I and okay for that.

**Comment by HuiyaChuang-NOAA** [comment] 2021-11-18 21:33
> @HuiyaChuang-NOAA I mean if the users will think this is a satellite remote sensing product since FDNSSTMP is in from the grib2 table for satellite remote sensing category. If you and @LydiaStefanova-NOAA think it is good, I and okay for that.

Fine with me.  I think Lydia should be fine too since she's the one pointing out the Grib2 ID for foundation temperature.
Thank you for running UPP regression tests for me and committing the changes.

**Comment by LydiaStefanova-NOAA** [comment] 2021-11-19 02:06
Thank you, @HuiyaChuang-NOAA and @WenMeng-NOAA Yes, I am also fine with the definition being from that category.

@HuiyaChuang-NOAA, could you please clarify about this part: 

> 6. Sent the plot to Lydia, Jessica who confirm the post processed foundation T is similar to the one plotted from model surface output.

For the plot of the post-processed foundation temperature that you had sent I had confirmed that it was very similar to the one plotted from surface netcdf output, **except** that it had some spurious vertical (oriented N to S) lines. Were these resolved, or were they found to be a plotting artifact?

**Comment by HuiyaChuang-NOAA** [comment] 2021-11-19 13:48
@LydiaStefanova-NOAA I used snipping software to save the plot and I think that's the artifacts.
I am going to dentist and then have 4 meetings but will make another plot this afternoon.

**Comment by HuiyaChuang-NOAA** [comment] 2021-11-23 21:46
@LydiaStefanova-NOAA please see attached new plot, generated by saving plot to a png file.
![GFS_FDNSSTMPsfc_2014101500F12](https://user-images.githubusercontent.com/56728916/143134148-fd4be9c1-c3fa-4f7e-a6e2-ac4c31108028.PNG)

**Comment by LydiaStefanova-NOAA** [comment] 2021-11-23 22:00
Thank you, @HuiyaChuang-NOAA - looks perfect! Shall I close this issue now?

**Comment by WenMeng-NOAA** [comment] 2021-11-24 00:40
@LydiaStefanova-NOAA You don't need to close this issue. Huiya will submit a PR to develop branch. After merging is done, I will close it. Thanks!

**Comment by LydiaStefanova-NOAA** [comment] 2021-11-24 00:53
@WenMeng-NOAA - thanks for explaining to me how it works!

**Closed as completed** 2021-12-02 20:27 UTC
