### ISSUE TITLE
github automated tests use deprecated features that will be disabled soon

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [NOAA-EMC/UPP#649] opened 2023-02-28 20:06 UTC
The github automated tests for UPP are generating warnings about features that will soon be disabled. This comes from the steps with "cache" in their names:

Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by WenMeng-NOAA** [comment] 2023-02-28 20:35
@AlexanderRichert-NOAA How could these warnings be addressed?  I also saw total cache storage hits limit at
https://github.com/NOAA-EMC/UPP/actions/caches
Should I manually clean up some caches? Thanks!

**Comment by AlexanderRichert-NOAA** [comment] 2023-02-28 21:22
I think the warnings are due to the usage of a relatively old version of the GitHub cache action. Maybe try "@v3" instead of "@v2"?

**Comment by WenMeng-NOAA** [comment] 2023-02-28 21:30
@SamuelTrahanNOAA Could you test the fix @AlexanderRichert-NOAA suggests in your PR #646? Thanks!

**Comment by SamuelTrahanNOAA** [comment] 2023-02-28 21:40
I changed all of the `@v2` to `@V3` in `.github/workflows/intel.yml` and pushed the change.

**Comment by SamuelTrahanNOAA** [comment] 2023-02-28 21:41
Apparently it needs to be `@v3` (lower-case)

**Comment by SamuelTrahanNOAA** [comment] 2023-02-28 21:52
Now I'm seeing new errors from the UPP build:

```
 ld: /home/runner/work/UPP/UPP/spack/var/spack/environments/upp-env/.spack-env/view/lib/libhdf5.so.310: undefined reference to `dlopen@GLIBC_2.34'
ld: /home/runner/work/UPP/UPP/spack/var/spack/environments/upp-env/.spack-env/view/lib/libhdf5.so.310: undefined reference to `fstat64@GLIBC_2.33'
ld: /home/runner/work/UPP/UPP/spack/var/spack/environments/upp-env/.spack-env/view/lib/libhdf5.so.310: undefined reference to `dlerror@GLIBC_2.34'
ld: /home/runner/work/UPP/UPP/spack/var/spack/environments/upp-env/.spack-env/view/lib/libhdf5.so.310: undefined reference to `stat64@GLIBC_2.33'
ld: /home/runner/work/UPP/UPP/spack/var/spack/environments/upp-env/.spack-env/view/lib/libhdf5.so.310: undefined reference to `dlclose@GLIBC_2.34'
ld: /home/runner/work/UPP/UPP/spack/var/spack/environments/upp-env/.spack-env/view/lib/libnetcdf.so: undefined reference to `fstat@GLIBC_2.33'
ld: /home/runner/work/UPP/UPP/spack/var/spack/environments/upp-env/.spack-env/view/lib/libhdf5.so.310: undefined reference to `dlsym@GLIBC_2.34'
ld: /home/runner/work/UPP/UPP/spack/var/spack/environments/upp-env/.spack-env/view/lib/libhdf5.so.310: undefined reference to `lstat64@GLIBC_2.33'
```

**Comment by SamuelTrahanNOAA** [comment] 2023-02-28 21:52
https://github.com/NOAA-EMC/UPP/actions/runs/4297640315/jobs/7490914467

**Comment by AlexanderRichert-NOAA** [comment] 2023-02-28 21:57
It's a bit of a shot in the dark, but you might try adding `sudo mv /usr/local/ /usr_local_mv` to the beginning of the build-upp step. If that doesn't do it then I have no idea.

**Comment by SamuelTrahanNOAA** [comment] 2023-02-28 22:13
When I do that, it can't find cmake:

```
/home/runner/work/_temp/649064c1-568f-4abe-8877-a61c4eee5d65.sh: line 8: cmake: command not found
```

**Comment by AlexanderRichert-NOAA** [comment] 2023-02-28 22:19
That's strange, since in the setup we ran "sudo apt install cmake". You could maybe try installing it through Spack. In any case, I think what's going on is that it's picking up on glibc's under /usr/local which shouldn't be getting used, so I think you'll need to find some way to get those out of the way (I suppose you could do something like `rm $(find /usr/local/ -name '*libc*')` but that seems awfully involved). You could also try adding `sudo apt install cmake` to the beginning of the build step to see if the problem is that it's not getting saved in the cache.

**Comment by SamuelTrahanNOAA** [comment] 2023-02-28 22:33
I'd rather merge the fixes we have now that *do* work and let the maintainer of this test suite fix the problem.

**Comment by WenMeng-NOAA** [comment] 2023-03-01 00:24
@SamuelTrahanNOAA Thanks for testing. Yes, I will process the final tests and work with @AlexanderRichert-NOAA for residual CI issue.

**Comment by edwardhartnett** [comment] 2024-07-22 12:26
GitHub is frequently deprecating versions of various actions, but the actions don't stop working. So I would suggest not worrying too much about warnings of the CI system for YML code.

**Comment by gspetro-NOAA** [comment] 2024-11-27 23:24
@WenMeng-NOAA Who is in charge of handling this issue, and can it be closed? I am trying to determine whether EPIC needs to take any action here (in which case, I'd add it to our project board). It seems like this might be an EMC issue though? And may be resolved?

**Comment by WenMeng-NOAA** [comment] 2024-11-28 01:07
@gspetro-NOAA Please confirm with the EMC library team @edwardhartnett and @AlexanderRichert-NOAA who implemented CI.

**Comment by AlexanderRichert-NOAA** [comment] 2024-11-28 01:16
I generally recommend moving to the most recent action versions (@v4 for both cache and checkout), both to avoid warnings and possible future deprecations. The alternative is to just wait for something to break and ignore the warnings.

**Comment by WenMeng-NOAA** [comment] 2024-11-28 01:21
@AlexanderRichert-NOAA Can you submit a PR for @v4? Thanks!

**Comment by AlexanderRichert-NOAA** [comment] 2024-11-28 01:29
@WenMeng-NOAA please see https://github.com/NOAA-EMC/UPP/pull/1100

**Closed as completed** 2024-11-29 18:55 UTC
Labels: enhancement
